name: deploy-web

on:
  push:
    tags: ["web[0-9].[0-9]+.[0-9]+"]

env:
  GKE_ZONE: asia-southeast1-a
  CLUSTER_NAME: main
  BUILD_ID: ${{ github.run_attempt }}-${{ github.run_number }}

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract releases version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: asia.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Push
        id: push
        env:
          REGISTRY: asia.gcr.io/${{ secrets.PROJECT_ID }}
          REPOSITORY: ${{ github.repository }}
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker pull $REGISTRY/$REPOSITORY:main
          docker tag $REGISTRY/$REPOSITORY:main $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    outputs:
      tag: ${{ env.RELEASE_VERSION }}

  patch:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Auth GCP"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: 'Get Credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}

      - name: "Patch K8S"
        env:
          APP_NAME: paiduay-web-core
          NAME_SPACE: waarn
          DOCKER_IMAGE: asia.gcr.io/${{ secrets.PROJECT_ID }}/${{ github.repository }}:${{ needs.push.outputs.tag }}
        run: |
          kubectl patch deployment ${APP_NAME} -n ${NAME_SPACE} --patch '{"spec":{"template":{"metadata":{"labels":{"version":"'${BUILD_ID}'"}},"spec":{"containers":[{"name":"'${APP_NAME}'","image":"'${DOCKER_IMAGE}'"}]}}}}'
